### ISSUE TITLE
How to use this API??

### ISSUE THREAD

**Issue by chiragpranami** [natsuite/NatStep#9]
Can you please show steps to use this API?

**Comment by olokobayusuf** [comment]
There are instructions for how to use the API on [the home page of the repository](https://github.com/olokobayusuf/Pedometer-API). Perhaps you forgot to scroll down. There is also [an included example](https://github.com/olokobayusuf/Pedometer-API/tree/1.1/Assets/Pedometer/Example).

**Comment by ksyao2002** [comment]
To get it to run, I had to copy the folder \Assets\Pedometer\Plugins in this repo (after cloning this repo) into a folder called plugins under assets in your project file. Then rename the plugins folder (from \Assets\Pedometer\Plugins) to Pedometer if you are getting the issue that Unity doesn't recognize Pedometer. To get it to run on android, I had to delete the folder ios in the plugins folder because it was giving errors. Any ideas why the ios doesn't build @olokobayusuf ?

**Comment by ReGaSLZR** [comment]
Just importing the latest Unity Package from here works: https://github.com/olokobayusuf/Pedometer-API/releases

**Comment by olokobayusuf** [comment]
You should import the latest `unitypackage` from the Releases page. If you have any errors, post them.

**Comment by ksyao2002** [comment]
Thanks for the responses. I imported the Pedometer 1.1 build mentioned by @ReGaSLZR but it kept giving me this error: "The type or namespace name 'Pedometer' could not be found (are you missing a using directive or an assembly reference?)" This error was also happening on the example C# script included in the package. I also noticed that under Plugins, there was only a build for iOS and none for Android. But when I cloned the github repo instead, the Plugins folder (\Assets\Pedometer\Plugins) did contain a build for android in addition to iOS. By putting the github repo instead in my plugins folder in my project, the error went away.

I figured out why my iOS build was not working: I had to manually click the libPedometer in Unity and, in the inspector, change the platform to iOS. By default it was "Any Platform." I was doing my Unity development on the Android build, so maybe that's why the iOS build did not have the correct import settings.

**Comment by olokobayusuf** [comment]
> Thanks for the responses. I imported the Pedometer 1.1 build mentioned by @ReGaSLZR but it kept giving me this error: "The type or namespace name 'Pedometer' could not be found (are you missing a using directive or an assembly reference?)" This error was also happening on the example C# script included in the package.

Can you share a screenshot of the error log? I can't reproduce this on my end.

> I also noticed that under Plugins, there was only a build for iOS and none for Android. But when I cloned the github repo instead, the Plugins folder (\Assets\Pedometer\Plugins) did contain a build for android in addition to iOS. By putting the github repo instead in my plugins folder in my project, the error went away.

![image](https://user-images.githubusercontent.com/17663473/84300913-ee16db80-ab20-11ea-90ed-780100355b9f.png)

I can't reproduce this; the Android and iOS libraries are right there. See the screenshot above.

**Comment by ksyao2002** [comment]
I'm not sure what I did initially, but when I tried to reproduce my own error, there was no more error, and also all the libraries are there. Sorry for the confusion and thanks for your time!

**Comment by TomasUtaravicius** [comment]
Do you know if this still works? I can download it and import it into the project, I probably get the same error as the guy above, but that is very easily fixed by changing cpu architecture on libPedometer.a . My problem is that the example scene doesn't call OnStep ever I tried building on couple different android phones.

**Comment by olokobayusuf** [comment]
@TomasUtaravicius I think the issue is because of the `ACTIVITY_RECOGNITION` permission not being specified in the `AndroidManifest.xml`. I'm working on adding that right now.
